# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install -t pre-commit -t pre-push

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        exclude: archetypes|docs|data|layouts|resources|source-git|static|themes/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/packit/pre-commit-hooks
    rev: 8db5a24e01b9f54aaa7a800f33c4b9aa619af1b9
    hooks:
      - id: check-rebase
        args:
          - https://github.com/packit/packit.dev.git
        stages: [manual, push]
